version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Before checkout
          command: |
            ls -al
            echo 'Before checkout'
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: The Second Step
          command: |
            ls -al
            echo '^^^The files in your repo^^^'
